spring:
  application:
    name: demo-lock
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
server:
  port: 0


#logging:
#    level:
#      io.github.jeeware.cloud.lock4j: trace

cloud:
  lock4j:
    instance-id: demo-${random.uuid}
#    mongo:
#      collection-name: my-locks

demo:
  cron:
    enabled: false
    duration-millis: 500